### ISSUE TITLE
self hosting not working on ubuntu & debian but working on macbook

### ISSUE THREAD

**Issue by junteudjio** [triggerdotdev/docker#8]
Hi guys,
Thanks for open sourcing this awesome product. 
I've followed the self hosting guide to the letter so far on 3 different brand new VPS (2 ubuntus & 1 debian) but it doesn't work.
All seems to work well until i visit localhost:3040 to realize it's a blank page or not accessible. (I've opened all the ports with ufw).
Only success I had was on my local macbook machine following the same steps. 
Any idea what could be the issue?
Cheers
Jr

**Comment by nicktrn** [comment]
Hey @junteudjio, by default all services including the webapp are only exposed on `localhost`:
```
    ports:
      - ${WEBAPP_PUBLISH_IP:-127.0.0.1}:3040:3030
```

I wouldn't recommend this for production use, but for a quick test you can set `WEBAPP_PUBLISH_IP=0.0.0.0` in your `.env` and restart the services. One of the dangerous things with exposing docker ports on a public interface is that _this will bypass ufw_ even if those ports are blocked.

**Comment by junteudjio** [comment]
thanks @nicktrn , it works. makes sense, I have a VPN in front of my VPS.
